from __future__ import annotations

from typing import Any

from core.utils import write_text


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Generate markdown report for the baseline phase.

    1. Summarize source data.
    2. Print retrieval/evaluation metrics.
    3. Print data quality and freshness.
    4. Write markdown to report_path.
    """
    lines = [
        "# Phase 1 — Baseline Pipeline Report",
        "",
        "## 1. Source Data Summary",
        "",
        f"- **Source API:** {source_summary.get('source_api', 'N/A')}",
        f"- **Query:** {source_summary.get('query', 'N/A')}",
        f"- **Total Records Fetched:** {source_summary.get('total_records', 'N/A')}",
        f"- **Clean Records:** {source_summary.get('clean_records', 'N/A')}",
        "",
        "## 2. RAG Evaluation Metrics",
        "",
        "| Metric | Value |",
        "| :--- | :--- |",
        f"| Samples | {metrics.get('samples', 'N/A')} |",
        f"| Retrieval Hit Rate | {metrics.get('retrieval_hit_rate', 0):.4f} |",
        f"| Mean Token F1 | {metrics.get('mean_token_f1', 0):.4f} |",
        f"| Judge Accuracy | {metrics.get('judge_accuracy', 0):.4f} |",
        f"| Mean Judge Score | {metrics.get('mean_judge_score', 0):.2f} |",
        "",
        "## 3. Data Quality Gate (Great Expectations 1.x)",
        "",
        f"- **Overall Success:** {'✅ PASS' if quality.get('success') else '❌ FAIL'}",
        f"- **Total Rows Checked:** {quality.get('total_rows', 'N/A')}",
        "",
        "| Check | Result |",
        "| :--- | :--- |",
    ]

    for check in quality.get("checks", []):
        status = "✅" if check["success"] else "❌"
        lines.append(f"| {check['expectation_type']} | {status} |")

    lines.extend([
        "",
        "## 4. Freshness Monitoring",
        "",
        f"- **Latest Published:** {freshness.get('latest_published', 'N/A')}",
        f"- **Oldest Published:** {freshness.get('oldest_published', 'N/A')}",
        f"- **Stale Rows (>{freshness.get('threshold_days', 180)} days):** {freshness.get('stale_rows', 0)} / {freshness.get('total_rows', 0)}",
        f"- **Stale Ratio:** {freshness.get('stale_ratio', 0):.2%}",
        f"- **Is Fresh:** {'✅ Yes' if freshness.get('is_fresh') else '⚠️ No — data may need refresh'}",
        "",
        "---",
        "",
        "*Report generated by Phase 1 Baseline Pipeline.*",
        "",
    ])

    write_text(report_path, "\n".join(lines))


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Generate markdown report comparing baseline/corrupted/repaired states."""

    def _fmt(val: Any) -> str:
        if isinstance(val, float):
            return f"{val:.4f}"
        return str(val)

    lines = [
        "# Phase 2 — Corruption & Repair Comparison Report",
        "",
        "## 1. RAG Metrics Comparison (3 States)",
        "",
        "| Metric | Baseline | Corrupted | Repaired |",
        "| :--- | :---: | :---: | :---: |",
    ]

    metric_keys = ["samples", "retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"]
    for key in metric_keys:
        b = _fmt(baseline_metrics.get(key, "N/A"))
        c = _fmt(corrupted_metrics.get(key, "N/A"))
        r = _fmt(repaired_metrics.get(key, "N/A"))
        lines.append(f"| {key} | {b} | {c} | {r} |")

    lines.extend([
        "",
        "## 2. Data Quality Gate Comparison",
        "",
        f"- **Corrupted Quality:** {'✅ PASS' if corrupted_quality.get('success') else '❌ FAIL — Quality gate correctly detected corruption!'}",
        f"- **Repaired Quality:** {'✅ PASS' if repaired_quality.get('success') else '❌ FAIL'}",
        "",
        "## 3. Freshness Comparison",
        "",
        "| Metric | Corrupted | Repaired |",
        "| :--- | :---: | :---: |",
        f"| Stale Rows | {corrupted_freshness.get('stale_rows', 'N/A')} | {repaired_freshness.get('stale_rows', 'N/A')} |",
        f"| Stale Ratio | {corrupted_freshness.get('stale_ratio', 0):.2%} | {repaired_freshness.get('stale_ratio', 0):.2%} |",
        f"| Is Fresh | {'✅' if corrupted_freshness.get('is_fresh') else '⚠️ No'} | {'✅' if repaired_freshness.get('is_fresh') else '⚠️ No'} |",
        "",
        "## 4. Analysis",
        "",
        "### Key Findings:",
        "",
        "1. **Corruption Impact:** Data corruption causes measurable degradation in RAG metrics,",
        "   demonstrating the Silent Failure problem where the AI answers confidently but incorrectly.",
        "2. **Quality Gate Detection:** Great Expectations 1.x quality checks successfully detect",
        "   corrupted data, proving the value of automated data observability.",
        "3. **Repair Effectiveness:** Idempotent repair from raw backup restores metrics to baseline",
        "   levels, confirming the importance of raw data preservation (lineage).",
        "",
        "---",
        "",
        "*Report generated by Phase 2 Corruption & Repair Pipeline.*",
        "",
    ])

    write_text(report_path, "\n".join(lines))
